### ISSUE TITLE
Asset types are wonky

### ISSUE THREAD

**Issue by reidrankin** [shapeshift/lib#178]
- `AbstractAsset` has way too much stuff in it (why does `lib` have a `color` field if it doesn't have a UI?)
- `OmittedTokenAssetFields` -- wat even? plz no
- `Asset`/`BaseAsset`/`AbstractAsset` all have a `chain` field which isn't generic, which means that you can e.g. construct a `BuildQuoteTxInput` without being statically sure that the wallet provided matches the chain type of the `sellAsset`

**Comment by 0xean** [comment]
@reidrankin - if you are willing to add some more details to this one, we could consider bountying it out.  LMK.

**Comment by reidrankin** [comment]
(wow, I must have been really tired when I wrote this)

**Comment by 0xdef1cafe** [comment]
as discussed, this is stale and @reidrankin will open a new issue with desired changes.
