### ISSUE TITLE
buildSendTransaction should choose from all types of UTXOs available for a given account

### ISSUE THREAD

**Issue by mrnerdhair** [shapeshift/lib#180]
UTXOs from all supported script types should be recognized and chosen from when spending from a given account.

This is *not* about combining a user's Legacy/Segwit P2SH/Segwit Native UTXO accounts and spending from their combined balance -- that's something we explicitly don't want to do. Instead, it's about being able to spend UTXOs of any script type from a given account, event if they're the "wrong" script type for that account. For example, it's perfectly possible on-chain to send a UTXO with a Segwit Native script to a supposedly "Legacy" account (i.e. to a `m/44'/0'/i'/0/n` address rather than `m/84'/0'/i'/0/n`). While we don't give out bech32 addresses for those accounts, if someone's somehow sent funds in that way we shouldn't prevent users from spending those UTXOs from that account.

More importantly, *not* doing this means we have to pass `tx.chainSpecific.accountType` to `buildSendTransaction`, which complicates our account abstraction.

This issue is, fundamentally, because blockbook -- and thus unchained, at the moment at least -- uses the "version bytes" of an xpub (i.e. whether it starts with `xpub`/`ypub`/`zpub`) to infer a script type and only looks up UTXOs of that specific type. (This is a bad idea, and *will* break long-term; taproot has a new account type but re-uses the `xpub` version bytes.) There are two possible solutions to that:
1) Fetch all three types from unchained in `buildSendTransaction`
2) Fetch only the xpub from unchained, and make unchained request all three types from blockbook

(The second approach would be preferable.)

**Comment by 0xean** [comment]
needs some more discussion to determine if this is the right path forward from a product perspective.

**Comment by reidrankin** [comment]
Not sure I understand the potential product angle here? For clarity, this isn't intended to involve combining balances from legacy/segwit/segwit p2sh/taproot accounts, just to make it so that any UTXO sent to an address is spendable, even if it was sent to the "wrong" type of address. (That said, it's not as much about saving potentially-lost user funds as it is avoiding the requirement for the buildSendTransation function to know what "account type" it's spending from.)

**Comment by mrnerdhair** [comment]
Discussed on 2/11/22 backlog grooming; concluded that we do want to do this, but it's not an immediate priority and probably won't happen until post-cosmos. Summary/title has been updated to be more specific and actionable.
