### ISSUE TITLE
(Staging) V2: Update Copy for FOX asset page

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/lib#238]
Add this copy to the FOX asset page on V2:

"FOX is an ERC-20 token created by ShapeShift which serves as the governance token for the ShapeShift DAO, token holders can vote on proposals relating to the operation and treasury of the DAO. The token supports and provides utility for a borderless, cross-chain crypto trading platform and portfolio manager for user self-sovereignty.

As the ShapeShift ecosystem expands, users will be able to earn FOX tokens for activity that generates revenue for the DAO via affiliate partnerships (i.e. earning yield, buying/selling/trading crypto and nft's, buying swag or a y.at, etc.). The ShapeShift DAO earns revenues, and the user earns FOX tokens which can represent entitlement to those revenues.

The total capped supply of FOX is 1,000,001,337 tokens."

**Comment by willyogo** [comment]
reached out to CoinGecko to see if they could update on their end 🙏

**Comment by 0xdef1cafe** [comment]
fixed upstream by coingecko. don't develop - delegate. thanks @willyogo
