### ISSUE TITLE
chainAdapters.byChain should return narrowed type

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/lib#321]
Currently, using `chainAdapters.ByChain` to get a chain-speciifc adapter will not return the properly narrowed type.
As a result, it is impossible to use `asset.chain.type` to discriminate the methods available in the chain adapter, even though an chain adapter is effectively available for its matching asset chain type.

Acceptation criteria:

- It is possible to use `asset.chain.type` as a discriminator for `ChainAdapters<T>` , to narrow it down to the specific `T` type

**Comment by gomesalexandre** [comment]
This should be done after the groundwork we do on chain-adapters.
Anything this low-level we do there in the meantime to e.g add type discriminations would most likely shoehorn types/logic that will be gone soon after.

**Comment by 0xApotheosis** [comment]
`byChain` no longer exists. The intent of this is covered by https://github.com/shapeshift/lib/issues/555
