### ISSUE TITLE
Ethereum token assets don't have the correct explorer URL attached

### ISSUE THREAD

**Issue by mrnerdhair** [shapeshift/lib#448]
### Overview

The AssetService's flattening logic currently sets the `explorer` property for every Ethereum token asset to `https://etherscan.io`, which while technically correct, is not the best kind of correct in this instance. It would be much more useful to have e.g. `https://etherscan.io/token/<token addr>` in that field for use by e.g. shapeshift/web#1188.

### Reference

This probably goes in `src/generateAssetData/ethTokens/ethereum.ts`.

### Acceptance Criteria

- Asset service is updated to include the relevant Etherscan explorer URL in the data of all Ethereum mainnet tokens

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by purelycrickets** [comment]
Needs a time estimate before this can be bountied.
