### ISSUE TITLE
bug - console spew on address validation

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/lib#487]
every keystroke on a send input form is throwing console errors

```
react_devtools_backend.js:3973 Error: 0xdef too short
    at Object.decode (index.js:158:15)
    at r.<anonymous> (CosmosSdkBaseAdapter.js:113:48)
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at t (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at r.<anonymous> (asyncToGenerator.js:21:12)
```

**Comment by gomesalexandre** [comment]
What's the intended behavior on this one? Do we want not to `console.error` when the input is shorter than the expected bech32, or to never console error at all?

**Comment by 0xdef1cafe** [comment]
@gomesalexandre at least debounce on input before validating - or maybe don't log at all, as a user typing into that box is kind of expected behavior?

**Comment by gomesalexandre** [comment]
> @gomesalexandre at least debounce on input before validating - or maybe don't log at all, as a user typing into that box is kind of expected behavior?

The rationale to logging was to be able to know exactly why the bech32 validation failed so in theory debouncing would help, but let's go with not logging errors at all, the errored button state should be enough to inform about the error
