### ISSUE TITLE
FOX Farm CTA

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/lib#500]
### Overview

As a user I want to be aware and be routed to the FOX farm page and all associated opportunities via the DeFi earn tab (https://app.shapeshift.com/defi/earn) on the web app.  This should be done via a CTA (call to action) banner. 

COPY: "Earn 60%+ APR* by farming your ETH-FOX liquidity pool tokens"

There should also be a button that says "Start Farming FOX" which will link to https://fox.shapeshift.com/fox-farming 

This banner/button should live at the top of the earn page. Please see the attached image for additional details/design.

https://www.sketch.com/s/5dcee031-1213-44a1-a94e-e3439cfb4d17/a/v8nnO9J 

![foxcta](https://user-images.githubusercontent.com/57505863/160482511-9e68bf7d-66a9-4172-954c-8eb264601528.png)

### Reference

Web. Need additional detail from engineering. 

### Acceptance Criteria

A/C:

A CTA banner will live at the top of the earn section with a clickable button linking to https://fox.shapeshift.com/fox-farming

### Need By Date

n/a

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Estimated effort

hours

### Sponsor / Stakeholder

@FOX_McCloud

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
@SS-FOX-McCloud can you please close this issue and reopen it under the web repo?

**Comment by SS-FOX-McCloud** [comment]
reopen in web https://github.com/shapeshift/web/issues/1550
