### ISSUE TITLE
handle more granular failures in investor-foxy getRebaseHistory

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/lib#501]
### Overview

We use Promise.allSettled but then don't make use of granular failures - we should fail as gracefully as possible, or just use Promise.all and fail entirely.

### Reference

https://github.com/shapeshift/lib/pull/497/files#diff-b2bd5bf9bdf02eebbdffb2a3b64a688e8e8be9bf13cd9298ab10bd84777e3cf8R926

### Acceptance Criteria

- More granular handling of web3 call failures in `investory-foxy` `getRebaseHistory` function

### Need By Date

n/a

**Comment by toshiSat** [comment]
So we decided to do this so charts would be "more right" than completely wrong.  What is the suggestion here, just return an empty array?

**Comment by 0xdef1cafe** [comment]
> So we decided to do this so charts would be "more right" than completely wrong. What is the suggestion here, just return an empty array?

yep as it'll still be wrong, but less wrong.
