### ISSUE TITLE
Asset Service Blacklist

### ISSUE THREAD

**Issue by Neverwas-dev** [shapeshift/lib#509]
### Overview

Currently the app will display any asset with a balance in your portfolio if it is on the asset list, and soon even assets not on the asset will be displayed too. There are a handful of known scam tokens that have been airdropped to many users' wallets and display misleading fiat values (ie. KICK and Minereum). As app maintainers, we want to be able to prevent known scam tokens from appearing in users' wallets and portfolios. Contributors should be able to make pull requests to an open source repo to add new known scam tokens to the blacklist.

### Reference

This was a pervious bounty that was [closed](https://github.com/shapeshift/lib/issues/353), but KICK is still showing in Production the asset KICK (0x426CA1eA2406c07d75Db9585F22781c096e3d0E0). 

The following assets no longer display in v2, even if users have a balance in their wallet:
KICK (0x426CA1eA2406c07d75Db9585F22781c096e3d0E0)
Minereum (0x426CA1eA2406c07d75Db9585F22781c096e3d0E0)
UNIH (0x4bf5dc91e2555449293d7824028eb8fe5879b689)
0x7761c09EA2DE3F7205Dba784Fd87Fd196E019D2A
0x6f0371247d21d7afad6e624f6e8dbb3bff0455c2
0xF9d25EB4C75ed744596392cf89074aFaA43614a8
0x0f8b6440a1f7be3354fe072638a5c0f500b044be
0x1412ECa9dc7daEf60451e3155bB8Dbf9DA349933
0x34278F6f40079eae344cbaC61a764Bcf85AfC949

### Acceptance Criteria

- blacklist.json file added somewhere in the asset service with a list of blacklisted asset ids, [using our asset id implementation](https://github.com/shapeshift/lib/blob/main/packages/caip/src/caip19/caip19.test.ts#L43) in the format ["eip155:1/erc20:0x426ca1ea2406c07d75db9585f22781c096e3d0e0", "eip155:1/erc20:0x4bf5dc91e2555449293d7824028eb8fe5879b689"]
- your implementation should filter out blacklisted tokens [somewhere in this function or another appropriate place](https://github.com/shapeshift/lib/blob/main/packages/asset-service/src/generateAssetData/generateAssetData.ts#L20)
- your implementation should be cross-chain and not ethereum specific
- add all the tokens listed above to the blacklist
- asset ids in the blacklist should be lowercase and not checksum format
- run the yarn generate script to regenerate asset data, verifying blacklisted tokens do not appear in the generatedAssetData.json file, commit the updated file
- add documentation to the repo how to add blacklisted tokens to the list
- raise a corresponding preemptive PR [in the web repo](https://github.com/shapeshift/web/pulls) and bump the asset service version in web after your PR in this repo is accepted and merged

### Need By Date

NA

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by NeOMakinG** [comment]
@Neverwas-dev Looks like KICK is not in the blacklist list
![image](https://user-images.githubusercontent.com/14963751/161697171-f6a1dc1e-a816-4426-a8d1-ab4a4b10a381.png)


Probably because the asset address in the description is wrong and I didn't take attention
