### ISSUE TITLE
CAIP2 - add ChainNamespace and ChainReference to input/output

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/lib#547]
### Overview

Add these as input and output types to maintain backwards compatibility and get us closer to using CAIPs throughout the stack.

### References and additional details

https://github.com/shapeshift/lib/blob/main/packages/caip/src/caip2/caip2.ts#L28

### Acceptance Criteria

Added as per reference

**Comment by 0xdef1cafe** [comment]
e.g. as discussed

```
export const assetNamespaces = [
  CW20 = 'cw20',
  CW721 = 'cw721',
  ERC20 = 'erc20',
  ERC721 = 'erc721',
  Slip44 = 'slip44',
  NATIVE = 'native',
  IBC = 'ibc'
] as const

export type AssetNamespace = typeof assetNamespaces[number]
```

**Comment by 0xApotheosis** [comment]
Note from defi:

---

things like `fromChainId` and fromAssetId need to also return `chainNamespace`, `chainReference`, `assetNamespace`, `assetReference`
similary `toChainId` and `toAssetId` need to accept them in lieu of chain and network

---
