### ISSUE TITLE
Independent Submodule Versioning

### ISSUE THREAD

**Issue by GMSteuart** [shapeshift/lib#579]
### Overview

As a developer, I want the ability to independently version the packages in this `lib` repository to have more control over the publishing process. Additionally, each submodule should be able to build separately without causing issues. Submodules should only be version bumped if a code or file change occurred in the package's directory.

### References and additional details

- `package.json` files will be useful
- semantic-release
- semantic-release-monorepo

### Acceptance Criteria

- [ ] All submodules successfully build
- [ ] Independent submodule versioning and publishing
- [ ] Implement test script for release using a local package manager

### Estimated effort

One day

**Comment by GMSteuart** [comment]
Missed opportunity to put @0xdef1cafe and @majorhayes under "References and additional details"

**Comment by 0xean** [comment]
closing per @0xdef1cafe
