### ISSUE TITLE
Remove `ChainTypes` from Swapper

### ISSUE THREAD

**Issue by DaoDev44** [shapeshift/lib#599]
### Overview

- We will need to remove `ChainTypes` with `chainId`(caip2) from Swapper to avoid any other implementations of swappers from using it.

### References and additional details

Swapper `api` and `ZrxSwapper`

### Acceptance Criteria

- Find a way to remove `ChainTypes` from Swappers.

### Estimated effort

Half a day - 1 day

**Comment by mrnerdhair** [comment]
For reference, see https://github.com/shapeshift/lib/pull/445, where I explored one potential approach.
