### ISSUE TITLE
Use Etherchain GasNow API in `EthereumChainAdapter.getFeeData`

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/lib#649]
### Overview

We are currently using gas price returned from [0x](https://gas.api.0x.org/). The prices returned are typically on the lower end and we would like to use [Etherchain GasNow API](https://etherchain.org/api/gasnow) for more accurate gas prices.

### References and additional details

Function to update: https://github.com/shapeshift/lib/blob/7a9506ee386d9750739f909d674a6230a2c037bf/packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts#L235

### Acceptance Criteria

- Replace 0x gas price with GasNow gas price
- Use GasNow `standard`, `fast`, `rapid` to replace 0x `low`, `standard`, `fast` respectively

**Comment by 0xean** [comment]
@kaladinlight - did this get resolved with the bug fixes?

**Comment by kaladinlight** [comment]
> @kaladinlight - did this get resolved with the bug fixes?

No, this was an improvement ticket though not high priority

**Comment by 0xdef1cafe** [comment]
closing as redundant, we can always reopen if we have reports of ethereum gas estimation being off
