### ISSUE TITLE
Replace ZrxSwapper gas price with Etherchain GasNow gas price

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/lib#650]
### Overview

In an effort to use the same gas price in both send and the zrx swapper, update `zrxBuildTrade` to use gas price from [Etherchain GasNow API](https://etherchain.org/api/gasnow).

### References and additional details

Contingent on: https://github.com/shapeshift/lib/issues/649 for option #2
`swap/v1/quote` call: https://github.com/shapeshift/lib/blob/7a9506ee386d9750739f909d674a6230a2c037bf/packages/swapper/src/swappers/zrx/zrxBuildTrade/zrxBuildTrade.ts#L95

### Acceptance Criteria

Option #1 (legacy transaction only):
- Call [EtherChain GasNow API](https://etherchain.org/api/gasnow)
- Replace `gasPrice` returned from 0x with `fast` from EtherChain

Option #2 (eip-1559 support):
- Call `EthereumChainAdapter.getFeeData`
- Replace `gasPrice` returned from 0x with `average` from `getFeeData`
- Return `maxFeePerGas` and `maxPriorityFeePerGas` on `Trade` so we can broadcast using EIP-1559 fees

**Comment by 0xdef1cafe** [comment]
closing w/ same rationale as https://github.com/shapeshift/lib/issues/649
