### ISSUE TITLE
Unchained-Client: Generic approve function parsing

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/lib#658]
### Overview

We are currently detecting approve contract calls against our yearn router contract only, but this is supported by many contracts and should be detected no matter what contract a user is interacting with.

### References and additional details

See the yearn parser for an example of how to instantiate an abi interface, and parse transaction input data

### Acceptance Criteria

- Detect approve contract call for any transaction that matches the function sigHash `approve(address,uint256)`

### Estimated effort

2 days.

**Comment by 0xApotheosis** [comment]
Turning into a bounty reserved for @vividwood.

**Comment by vividwood** [comment]
So, I created simple subparser for approve sighash and got following result.
![image](https://user-images.githubusercontent.com/101632255/169588265-486f47b3-61ab-42d7-b2a4-ff9a99a81cdc.png)
But, in my opinion this looks kinda useless without showing an asset. 
So I changed api a little and got this
![image](https://user-images.githubusercontent.com/101632255/169588712-c94968da-c072-4b10-88dd-b2d84d175acd.png)
There is no way to know contract address transaction interacted with, so I had to extend `StandardTxMetadata`. We can discuss other ways to send contract address if we go in this direction. Or I can just stick to first example.
@kaladinlight @0xApotheosis  what do you think?

**Comment by kaladinlight** [comment]
> So, I created simple subparser for approve sighash and got following result. ![image](https://user-images.githubusercontent.com/101632255/169588265-486f47b3-61ab-42d7-b2a4-ff9a99a81cdc.png) But, in my opinion this looks kinda useless without showing an asset. So I changed api a little and got this ![image](https://user-images.githubusercontent.com/101632255/169588712-c94968da-c072-4b10-88dd-b2d84d175acd.png) There is no way to know contract address transaction interacted with, so I had to extend `StandardTxMetadata`. We can discuss other ways to send contract address (like adding `to`) if we go in this direction. Or I can just stick to first (asset-less) example. @kaladinlight @0xApotheosis what do you think?

I agree that knowing what asset is being approved looks a lot better than just tagging as generic approve. The intention was to be able to extend the StandardTxMetadata with potential parser specific metadata and be able to use type narrowing based on discriminated unions. This has not been fully built out at this time however. The other possibility we have is to create the asset id from a combination of `chainId` and using the `to` address as the `assetReference` and the `assetNamespace` as `AssetNamespace.ERC20`. This way we can make the assumption that we are detecting erc20 abi approve contract calls via this generic parser. Let me know your thoughts on these two strategies given the bounty timeframe and we can see what @0xApotheosis weighs in with as well

**Comment by 0xApotheosis** [comment]
Agree with you there @kaladinlight re: extending `StandardTxMetadata` in a way that we can discriminate on the client is ideal, and might be possible to do a working version of it in this PR - I'll lean on @vividwood for your thoughts on including that in this bounty.

The second option could work too, though it doesn't feel as extensible to me as a broader pattern.

**Comment by vividwood** [comment]
> The other possibility we have is to create the asset id from a combination of chainId and using the to address as the assetReference and the assetNamespace as AssetNamespace.ERC20. This way we can make the assumption that we are detecting erc20 abi approve contract calls via this generic parser.

That's pretty much what I'm doing.
I don't know why currently `StandardTx` has no `to` field, probably you have some reason for this, but having it there would solve problem without extending `data` field.

https://github.com/shapeshift/lib/blob/5dd6969e0eb0a2d7cf97d990c643c408f3ea3f17/packages/unchained-client/src/types.ts#L66-L78

> I agree that knowing what asset is being approved looks a lot better than just tagging as generic approve. The intention was to be able to extend the StandardTxMetadata with potential parser specific metadata and be able to use type narrowing based on discriminated unions. This has not been fully built out at this time however. I would want to be cognizant about choosing to extend StandardTxMetadata in a way that we can narrow appropriately client side rather than it turning into a dumping ground for optional extra information for all the more unique parsers.

I can do something like this:

```typescript
enum TxParser {
  Cosmos = 'cosmos',
  Yearn = 'yearn',
  UniV2 = 'uniV2',
  ZRX = 'zrx',
  Thor = 'thor',
  Foxy = 'foxy',
  WETH = 'weth'
  Generic = 'generic'
}

type TxMetadata = StandardTxMetadata | GenericTxMetadata

interface StandardTxMetadata {
  method?: string
  parser: Exclude<TxParser, TxParser.Generic>
}

type GenericTxMetadata = ApproveTxMetadata

interface ApproveTxMetadata {
  method: "approve",
  parser: TxParser.Generic,
  // other stuff
}

```

That should help narrow types we need on client while keeping old parsers the same, altough I think this could be an overkill for now.

**Comment by kaladinlight** [comment]
> > The other possibility we have is to create the asset id from a combination of chainId and using the to address as the assetReference and the assetNamespace as AssetNamespace.ERC20. This way we can make the assumption that we are detecting erc20 abi approve contract calls via this generic parser.
> 
> That's pretty much what I'm doing. I don't know why currently `StandardTx` has no `to` field, probably you have some reason for this, but having it there would solve problem without extending `data` field.
> 
> https://github.com/shapeshift/lib/blob/5dd6969e0eb0a2d7cf97d990c643c408f3ea3f17/packages/unchained-client/src/types.ts#L66-L78
> 
> > I agree that knowing what asset is being approved looks a lot better than just tagging as generic approve. The intention was to be able to extend the StandardTxMetadata with potential parser specific metadata and be able to use type narrowing based on discriminated unions. This has not been fully built out at this time however. I would want to be cognizant about choosing to extend StandardTxMetadata in a way that we can narrow appropriately client side rather than it turning into a dumping ground for optional extra information for all the more unique parsers.
> 
> I can do something like this:
> 
> ```ts
> enum TxParser {
>   Cosmos = 'cosmos',
>   Yearn = 'yearn',
>   UniV2 = 'uniV2',
>   ZRX = 'zrx',
>   Thor = 'thor',
>   Foxy = 'foxy',
>   WETH = 'weth',
>   Generic = 'generic'
> }
> 
> type TxMetadata = StandardTxMetadata | GenericTxMetadata
> 
> interface StandardTxMetadata {
>   method?: string
>   parser: Exclude<TxParser, TxParser.Generic>
> }
> 
> type GenericTxMetadata = ApproveTxMetadata
> 
> interface ApproveTxMetadata {
>   method: "approve",
>   parser: TxParser.Generic,
>   // other stuff
> }
> ```
> 
> This should help narrow types we need on client while keeping old parsers the same, altough I think this could be an overkill for now. But yeah, we will need to do it anyway at some point, so maybe it is better to do it now.

The standard transaction is comprised of multiple potential transfers, so to avoid the case where you may have multiple top level to addresses, the from/to is constrained to the specific value transfer detected. As there are no actual value transfers (just gas), we don't end up returning this information anywhere which would be where the metadata would ideally come into play.

I think building out a way to extend the metadata for unique parsers and allow for discrimination would be the desired path forward.

This setup makes a little more sense to me I think:
```
export enum TxParser {
  Cosmos = 'cosmos',
  Yearn = 'yearn',
  UniV2 = 'uniV2',
  ZRX = 'zrx',
  Thor = 'thor',
  Foxy = 'foxy',
  WETH = 'weth',
  ERC20_APPROVE = 'erc20Approve'
}

export type TxMetadata = StandardTxMetadata | ApproveTxMetadata

export interface BaseTxMetadata {
  method?: string
  parser: string
}

export interface StandardTxMetadata extends BaseTxMetadata {
  parser: Exclude<TxParser, TxParser.ERC20_APPROVE>
}

export interface ApproveTxMetadata extends BaseTxMetadata {
  parser: TxParser.ERC20_APPROVE
  method: 'approve'
  contract: string
}
```

The only annoyance is having to add to the `TxMetadata` union and the exclude list for each new specific tx metadata type. I think it is a place to start though and we can always try to incorporate more typescript magic to make it dynamically driven off a given set of standard and specific tx parsers. I wasn't able to figure out a way easily at first take

**Comment by vividwood** [comment]
> > > The other possibility we have is to create the asset id from a combination of chainId and using the to address as the assetReference and the assetNamespace as AssetNamespace.ERC20. This way we can make the assumption that we are detecting erc20 abi approve contract calls via this generic parser.
> > 
> > 
> > That's pretty much what I'm doing. I don't know why currently `StandardTx` has no `to` field, probably you have some reason for this, but having it there would solve problem without extending `data` field.
> > https://github.com/shapeshift/lib/blob/5dd6969e0eb0a2d7cf97d990c643c408f3ea3f17/packages/unchained-client/src/types.ts#L66-L78
> > 
> > > I agree that knowing what asset is being approved looks a lot better than just tagging as generic approve. The intention was to be able to extend the StandardTxMetadata with potential parser specific metadata and be able to use type narrowing based on discriminated unions. This has not been fully built out at this time however. I would want to be cognizant about choosing to extend StandardTxMetadata in a way that we can narrow appropriately client side rather than it turning into a dumping ground for optional extra information for all the more unique parsers.
> > 
> > 
> > I can do something like this:
> > ```ts
> > enum TxParser {
> >   Cosmos = 'cosmos',
> >   Yearn = 'yearn',
> >   UniV2 = 'uniV2',
> >   ZRX = 'zrx',
> >   Thor = 'thor',
> >   Foxy = 'foxy',
> >   WETH = 'weth',
> >   Generic = 'generic'
> > }
> > 
> > type TxMetadata = StandardTxMetadata | GenericTxMetadata
> > 
> > interface StandardTxMetadata {
> >   method?: string
> >   parser: Exclude<TxParser, TxParser.Generic>
> > }
> > 
> > type GenericTxMetadata = ApproveTxMetadata
> > 
> > interface ApproveTxMetadata {
> >   method: "approve",
> >   parser: TxParser.Generic,
> >   // other stuff
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This should help narrow types we need on client while keeping old parsers the same, altough I think this could be an overkill for now. But yeah, we will need to do it anyway at some point, so maybe it is better to do it now.
> 
> The standard transaction is comprised of multiple potential transfers, so to avoid the case where you may have multiple top level to addresses, the from/to is constrained to the specific value transfer detected. As there are no actual value transfers (just gas), we don't end up returning this information anywhere which would be where the metadata would ideally come into play.
> 
> I think building out a way to extend the metadata for unique parsers and allow for discrimination would be the desired path forward.
> 
> This setup makes a little more sense to me I think:
> 
> ```
> export enum TxParser {
>   Cosmos = 'cosmos',
>   Yearn = 'yearn',
>   UniV2 = 'uniV2',
>   ZRX = 'zrx',
>   Thor = 'thor',
>   Foxy = 'foxy',
>   WETH = 'weth',
>   ERC20_APPROVE = 'erc20Approve'
> }
> 
> export type TxMetadata = StandardTxMetadata | ApproveTxMetadata
> 
> export interface BaseTxMetadata {
>   method?: string
>   parser: string
> }
> 
> export interface StandardTxMetadata extends BaseTxMetadata {
>   parser: Exclude<TxParser, TxParser.ERC20_APPROVE>
> }
> 
> export interface ApproveTxMetadata extends BaseTxMetadata {
>   parser: TxParser.ERC20_APPROVE
>   method: 'approve'
>   contract: string
> }
> ```
> 
> The only annoyance is having to add to the `TxMetadata` union and the exclude list for each new specific tx metadata type. I think it is a place to start though and we can always try to incorporate more typescript magic to make it dynamically driven off a given set of standard and specific tx parsers. I wasn't able to figure out a way easily at first take

I just realized that all tx types are getting overwritten in `chain-adapters` so we need to implement all of this there or somewhere further down the line
