### ISSUE TITLE
Bitcoin chain adapter - create bitcoin swap tx

### ISSUE THREAD

**Issue by elmutt** [shapeshift/lib#691]
### Overview

The Bitcoin chain adapter needs a new function (similar to buildSendTx) that generates a thorchain swap transaction.

### References and additional details

Existing buildSendTransaction() lives here: 

https://github.com/shapeshift/lib/blob/main/packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.ts#L91

Use this as a reference for adding the new function

### Acceptance Criteria

Create an unsigned bitcoin transaction that will perform a thorchain swap given:

sellAssetId, buyAssetId, sellAmount, desired rate, maximum slippage tolerance

Test that this tx works correctly on chain and add relevant unit tests

**Comment by 0xdef1cafe** [comment]
closing per @elmutt
