### ISSUE TITLE
Ethereum thor trade parsing

### ISSUE THREAD

**Issue by elmutt** [shapeshift/lib#694]
### Overview

Detect thorchain trade in the eth parser and include relevant metadata with tx (trade details so we can match it up with the other transaction on the other chain)

### References and additional details

We already have some work started on the eth parser for thorchain already

https://github.com/shapeshift/lib/blob/main/packages/unchained-client/src/ethereum/parser/thor.ts

curent functionality is unknown

Trade metadata for attaching to the tx will probably have to come from a midgard call

### Acceptance Criteria

The eth sub parser attaches useful metadata about the trade to thortrade related eth txs

it should work for both eth and erc20 sends & receives

**Comment by 0xdef1cafe** [comment]
closing until we do "blockchain activity" type epic and have the concept of a "trade" which points to multiple transactions on multiple chains
