### ISSUE TITLE
Bitcoin thor trade parsing

### ISSUE THREAD

**Issue by elmutt** [shapeshift/lib#695]
### Overview

Detect thorchain trade in the btc parser and include relevant metadata with tx (trade details so we can match it up with the other transaction on the other chain)

### References and additional details

Our current bitcoin parser:

https://github.com/shapeshift/lib/blob/main/packages/unchained-client/src/bitcoin/parser/index.ts

Trade metadata for attaching to the tx will probably have to come from a midgard call

### Acceptance Criteria

The btc parser attaches useful metadata about the trade to thortrade related btc txs

Should work for sends & receives that are part of thor trades

**Comment by 0xdef1cafe** [comment]
closing until we do "blockchain activity" type epic and have the concept of a "trade" which points to multiple transactions on multiple chains

**Comment by 0xdef1cafe** [comment]
related https://github.com/shapeshift/lib/issues/694
