### ISSUE TITLE
Spike: Determine which wallets will support thor trades out of the box

### ISSUE THREAD

**Issue by elmutt** [shapeshift/lib#713]
### Overview

Determine which wallets will support thor trades out of the box

### References and additional details

Determine which wallets will support thor trades out of the box.

Check: Portis, Keepkey, Native and all the others to work with thor trading

### Acceptance Criteria

Determine which wallets will support thor trades out of the box:

1) connect wallet
2) enable thorchain feature flag
3) attempt trades for:
 - eth to any thorchain asset (if the wallet supports eth)
 - erc20 to any thoirchain asset (if the wallet supports erc20)
 - all utxo asset to any thorchain asset (if the wallet supports those utxo assets)
 - atom to any thorchain asset (if the wallet supports atom)

Make note of which wallets work and fail for each

4) The wallet is supported if the trade completes successfully through the thorchain swapper
5) repeat steps 1-4 for all wallets

**Comment by tshifty** [comment]
@elmutt "attempt trade from eth -> fox (the default pair)" Does this need to be the default pair? ETH to BTC is a lot cheaper in fee's than an ETH to ERC-20 ThorTrade

**Comment by elmutt** [comment]
> @elmutt "attempt trade from eth -> fox (the default pair)" Does this need to be the default pair? ETH to BTC is a lot cheaper in fee's than an ETH to ERC-20 ThorTrade

I updated the testing instructions. We also want to test other trade cases as well to know exactly what wallets support what

**Comment by 0xdef1cafe** [comment]
thinking out loud - metamask + snaps might be a lower lift than adding additional chain support via XDEFI

**Comment by DiggyDiggy2** [comment]
testing the different wallets should allow us to close this ticket. its a bit late to spike

**Comment by Neverwas-dev** [comment]
I was able to do swaps on Native wallet, didn't work for XDEFI as if yet. More Comments and screen shots in the discord thread. Tested trades ETH to UTXO, UTXO to UTXO ETH to ATOM, UTXO to ATOM

**Comment by 0xdef1cafe** [comment]
closing in favor of https://github.com/shapeshift/hdwallet/issues/438

@shapeshift/operations can work with support to create articles to manage user expectations
