### ISSUE TITLE
CowSwap : update swappercli with CowSwapper

### ISSUE THREAD

**Issue by chxash** [shapeshift/lib#727]
### Overview

We want to be able to test `CowSwapper` trade cycle with `swappercli ` (similarly to what is being done currently for `ZrxSwapper`)
This is dependent on almost all api being implemented except approval.
Some lines may be left commented in `swappercli` in order to let the developper choose which scenario to run (0x or CowSwap).

### References and additional details

See https://github.com/shapeshift/lib/issues/702 for more context

### Acceptance Criteria

- swappercli can be used to test `CowSwapper`

### Estimated effort

2 hours

**Comment by 0xdef1cafe** [comment]
closing as this isn't really a specific task and swappercli has been constantly updated with small changes as cowswap progresses
