### ISSUE TITLE
Swapper in Lib: Add getAvailableAssets to SwapperManager

### ISSUE THREAD

**Issue by toshiSat** [shapeshift/lib#74]
We will need something to get a call to get available assets using all swappers in the manager

**Comment by 0xean** [comment]
blocked until thor chain swapper.

**Comment by theoboldfrazier** [comment]
@DaoDev44 I know you're working on thorchain swapper. Is this still an issue? I don't think this applies anymore due to architecture changes. If this doesn't apply anymore can you close this issue?

**Comment by 0xean** [comment]
@DaoDev44 please see above. Can we close this?

**Comment by DaoDev44** [comment]
@theoboldfrazier @0xean yes this can be closed. I'll close now.
