### ISSUE TITLE
Figure out how to add affiliate address to thor tx memos

### ISSUE THREAD

**Issue by elmutt** [shapeshift/lib#749]
### Overview

Figure out how to add affiliate address to thor tx.

How does it work for bitcoin when we are limited to 80 characters in op return?

### References and additional details

How does it work for bitcoin when we are limited to 80 characters in op return?

### Acceptance Criteria

How does it work for bitcoin when we are limited to 80 characters in op return?

**Comment by 0xdef1cafe** [comment]
still valid

**Comment by 0xdef1cafe** [comment]
confirmed we own the `ss` thorname and have control of it and that it can be used for memo's for affiliate fees
