### ISSUE TITLE
CowSwap : replace '/api/v1/market' call with '/api/v1/quote' in getUsdRate method

### ISSUE THREAD

**Issue by chxash** [shapeshift/lib#759]
### Overview

 '/api/v1/market' has just been deprecated so it may be better to use '/api/v1/quote' instead.

### References and additional details

https://api.cow.fi/docs/#/default/get_api_v1_markets__baseToken___quoteToken___kind___amount_

### Acceptance Criteria

getUsdRate method is still working and the usdRate estimation is still correct

### Estimated effort

3 hours

**Comment by 0xdef1cafe** [comment]
@chxash is this still valid or has this been implemented?

**Comment by chxash** [comment]
@0xdef1cafe still valid yes, rather a "nice to have" than anything

**Comment by 0xdef1cafe** [comment]
@chxash i hope you don't mind that i assigned you to this one - i'm going to pick up the tx parsing tickets, as IMO, they're a blocker to shipping, but it would be nice if we could get this one closed out as a low priority after we ship just to tie up loose ends such that we're not using deprecated endpoints in brand new code.

**Comment by chxash** [comment]
@0xdef1cafe no problem, thank you for assigning me, will work on this asap !
