### ISSUE TITLE
Avalanche Chain Adapter

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/lib#814]
### Overview

Create an avalanche chain adpater for interacting with avalanche chain from web

### References and additional details

Should closely resemble the eth chain adapter

### Acceptance Criteria

- Implement ChainAdapter interface

**Comment by 0xdef1cafe** [comment]
blocked until blockbook is synced @kaladinlight 

will require some small changes to the ethereum chain adapter to remove hard coding. follow the CosmosSDKBaseAdapter pattern if possible.
