### ISSUE TITLE
Abstract EVM tx parsing

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/lib#815]
### Overview

The ethereum and avalanche standard tx parser should look pretty much identical. As we add more evm chains it will be nice to have shared logic abstracted and extensible for unique chain needs

### References and additional details

Current evm chains: ethereum, avalanche

### Acceptance Criteria

- Abstract shared functionality where it makes sense
- Ensure base functionality/logic can be easily extensible to support chain specific needs

**Comment by 0xdef1cafe** [comment]
let's copypasta ethereum parsers for now, and we can abstract this if and when we do a 3rd evm chain
