### ISSUE TITLE
Abstract EVM chain adapter

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/lib#816]
### Overview

With the addition of new evm chains, we will want to be able to have some shared base chain adapter logic that can be extended for chain specific needs

### References and additional details

Current evm chains: ethereum, avalanche

### Acceptance Criteria

- Base EVM chain adapter
- Base class should be extensible for chain specific needs

**Comment by 0xdef1cafe** [comment]
same as tx parser; let's copypasta the ethereumchainadapter now, and do this abstraction for the third+ evm chain
