### ISSUE TITLE
Cleanup `chainIdToFeeAssetId`

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/lib#875]
### Overview

Currently, `chainIdToFeeAssetId` is used in web to get the fee/native AssetId for a given `ChainId`.

However, chain-adapters contain a `getFeeAssetId` method that will return that same `AssetId`.

It should be used instead, and the `chainIdToFeeAssetId` function removed.

### References and additional details

https://github.com/shapeshift/lib/search?q=getFeeAssetId

### Acceptance Criteria

- chainIdToFeeAssetId is removed
- Web consumptions are replaced with some usage of chain-adapters e.g `getChainAdapters().get(chainId)?.getFeeAssetId()`

**Comment by 0xdef1cafe** [comment]
closed by https://github.com/shapeshift/web/pull/2159 ?

**Comment by gomesalexandre** [comment]
> closed by [shapeshift/web#2159](https://github.com/shapeshift/web/pull/2159) ?

Almost, this one-liner will do https://github.com/shapeshift/lib/pull/907
