### ISSUE TITLE
Hosted midgard

### ISSUE THREAD

**Issue by elmutt** [shapeshift/lib#922]
### Overview

We havent been able to find more than 1 reliable public midgard. 

We need a solution for self hosting midgard or taxistake midgard

### References and additional details

n/a

### Acceptance Criteria

n/a

**Comment by 0xdef1cafe** [comment]
to add some color to this

* if we *don't* host our own node, we can't ship thorchain until we rely on multiple public midgards nodes. it's *way* too easy to spin up a malicious midgard that serves malicious vault addresses. we checked with thorchain discord and they pointed us to 3 public nodes, only 1 of which is consistent and reliable.
* if we *do* host our own node, we can trust it and don't need round-robin logic.

**Comment by 0xdef1cafe** [comment]
closed in favor of https://github.com/shapeshift/unchained/issues/474
