### ISSUE TITLE
Correctly parse tx history?

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/lib#925]
### Overview

Placeholder ticket until we have more info - @elmutt 

### References and additional details

.

### Acceptance Criteria

.

**Comment by elmutt** [comment]
We plan on handling this soon as part of the osmosis bounty. WIll need to update the existing cosmos parser or potentially make a new one. Will coordinate with @kaladinlight on the best way of doing this

**Comment by 0xdef1cafe** [comment]
plz be aware of https://github.com/shapeshift/lib/pull/944 while working on this
