### ISSUE TITLE
Idle Finance Multi Account Support

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/lib#943]
### Overview

Idle requires multi account support before being enabled.

### References and additional details

* Spec inherited from https://github.com/shapeshift/lib/issues/987
* Refer to other tickets for reference implementations here https://github.com/shapeshift/lib/milestone/21

### Acceptance Criteria

* We meet the criteria in #987 

### Estimated effort

1 day

**Comment by 0xdef1cafe** [comment]
blocked by https://github.com/shapeshift/lib/issues/999

**Comment by 0xdef1cafe** [comment]
unblocked
