### ISSUE TITLE
More accurate fee estimations for bch

### ISSUE THREAD

**Issue by elmutt** [shapeshift/lib#959]
I did not feel it was worth the time trying to figure out exactly whats going on (coinselect not working how we expect maybe?) when BCH is a less common coin AND fees are already very low for bch

_Originally posted by @elmutt in https://github.com/shapeshift/lib/pull/949#discussion_r940737431_

**Comment by 0xApotheosis** [comment]
Closing this.

I'm not sure what the specific issue was, but I'd wager it's been resolved by https://github.com/shapeshift/lib/pull/1080.
